export interface Refaccion {
    ID: number,
    idModelo: string,
    Descripcion: string,
    TipoRefaccion: string,
    TipoForma: string,
    Unidad: string,
    Modelo: string,
    Anio: string,
    Posicion: string,
    DiametroInt: string,
    DiametroExt: string,
    Largo: string,
    LargoTot: string,
    info: string,
}
